Sprint2
ClevertecFrontendLab/sprint2-S4mm4ael pull request #1
Opened 2023-02-09 22:45 UTC by S4mm4ael

2023-02-09 22:58 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675983524/slider%20one%20foto%20768px.png)

2023-02-09 23:15 UTC, klichkovskiy requested changes

2023-02-09 23:15 UTC, klichkovskiy commented on src/components/burger/burger.tsx
> +    <button
![image](https://user-images.githubusercontent.com/62481116/217960086-ac8cba21-1183-45df-8c11-d635ee376ed1.png)
сделай нормальную кнопку а не чтобы линии искать (у тебя кнопка это три линии, а все что между нет)

2023-02-09 23:15 UTC, klichkovskiy commented on src/components/navigation-list/navigation-list.tsx
> +      data-test-id='burger-navigation'
![image](https://user-images.githubusercontent.com/62481116/217960288-d113c378-0469-4784-8ad4-c153d1d34b42.png)
Клик вне данной области закрывает это меню

2023-02-10 00:19 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 90%.
Общее количество тестов: 10.
Количество непройденных тестов: 1.
***
**Test width 1440px -- test layout burger-menu (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/Test%20width%201440px%20--%20test%20layout%20burger-menu%20(failed).png)
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/app%20burger-menu%20open%20768px.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675988399/slider%20one%20foto%20768px.png)

2023-02-10 01:35 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/S4mm4ael/1675992959/slider%20one%20foto%20768px.png)

2023-02-10 06:52 UTC, klichkovskiy approved these changes
Удачи на 3 спринте!

2023-02-10 06:53 UTC, merged